import type { FinanceAssumptions, Decision, OpenQuestion, NextAction, Studio, SpaceImage, LibraryItem, Scenario, RoadmapItem, ProductConcept } from "./schemas";
import { ensureProductVersionFields, type ProductInput } from "./engine/product-catalog";
import { syncFlexiblePackageMixFromServiceDemand } from "./engine/service-demand-mix";

const RAW_SAMPLE_PRODUCTS: ProductInput[] = [
  {
    id: "drop-in",
    name: "Drop-in",
    type: "drop_in",
    price: 1695,
    gstTreatment: "exclusive",
    gstFollowsGlobal: true,
    creditsIncluded: 1,
    packageMixPct: 10,
    serviceDemandPct: 10,
    peakEligible: true,
    recurring: false,
    discountPct: 0,
    classEligibility: [],
    standingSpotMaxSeatsPerClass: 1,
    packRules: {
      validityValue: 4,
      validityUnit: "weeks",
      validityBeginsFrom: "activation",
      activationDeadlineDays: 30,
      activationPolicy: "expire_if_not_activated",
      eligibleClassTypes: [],
      eligibleTimeBands: ["peak", "standard", "off_peak"],
      expectedRedemptionRatePct: 100,
      expectedBreakageRatePct: 0,
      expectedCancellationRatePct: 5,
      expectedNoShowRatePct: 3,
      expectedPeakBookingSharePct: 55,
      transferable: false,
      refundable: false,
      expectedSalesVolumePerMonth: 0,
      active: true,
      displayOrder: 1,
    },
  },
  {
    id: "8-pack",
    name: "8 Credit Pack",
    type: "credit_pack",
    price: 11525,
    gstTreatment: "exclusive",
    gstFollowsGlobal: true,
    creditsIncluded: 8,
    packageMixPct: 45,
    serviceDemandPct: 45,
    peakEligible: true,
    recurring: false,
    discountPct: 0,
    classEligibility: [],
    expectedRedemptionRatePct: 90,
    expectedBreakagePct: 10,
    standingSpotMaxSeatsPerClass: 1,
    packRules: {
      validityValue: 8,
      validityUnit: "weeks",
      validityBeginsFrom: "activation",
      activationDeadlineDays: 30,
      activationPolicy: "expire_if_not_activated",
      eligibleClassTypes: [],
      eligibleTimeBands: ["peak", "standard", "off_peak"],
      expectedRedemptionRatePct: 90,
      expectedBreakageRatePct: 10,
      expectedCancellationRatePct: 5,
      expectedNoShowRatePct: 3,
      expectedPeakBookingSharePct: 50,
      transferable: false,
      refundable: false,
      expectedSalesVolumePerMonth: 8,
      active: true,
      displayOrder: 2,
    },
  },
  {
    id: "16-pack",
    name: "16 Credit Pack",
    type: "credit_pack",
    price: 21695,
    gstTreatment: "exclusive",
    gstFollowsGlobal: true,
    creditsIncluded: 16,
    packageMixPct: 30,
    serviceDemandPct: 30,
    peakEligible: true,
    recurring: false,
    discountPct: 0,
    classEligibility: [],
    expectedRedemptionRatePct: 88,
    expectedBreakagePct: 12,
    standingSpotMaxSeatsPerClass: 1,
    packRules: {
      validityValue: 12,
      validityUnit: "weeks",
      validityBeginsFrom: "activation",
      activationDeadlineDays: 30,
      activationPolicy: "expire_if_not_activated",
      eligibleClassTypes: [],
      eligibleTimeBands: ["peak", "standard", "off_peak"],
      expectedRedemptionRatePct: 88,
      expectedBreakageRatePct: 12,
      expectedCancellationRatePct: 5,
      expectedNoShowRatePct: 3,
      expectedPeakBookingSharePct: 45,
      transferable: false,
      refundable: false,
      expectedSalesVolumePerMonth: 4,
      active: true,
      displayOrder: 3,
    },
  },
  {
    id: "private-session",
    name: "Private Session",
    type: "private",
    price: 4000,
    gstTreatment: "exclusive",
    gstFollowsGlobal: true,
    creditsIncluded: 0,
    packageMixPct: 0,
    serviceDemandPct: 15,
    peakEligible: true,
    recurring: false,
    discountPct: 0,
    classEligibility: [],
    standingSpotMaxSeatsPerClass: 1,
    privateRules: {
      durationMinutes: 55,
      clientsPerSession: 1,
      reformersOccupied: 1,
      instructorCostPerHour: 0,
      otherDirectVariableCost: 30,
      eligibleTimeBands: ["standard", "off_peak"],
      expectedSessionsPerMonth: 0,
      expectedCancellationRatePct: 5,
      expectedNoShowRatePct: 3,
    },
  },
  {
    id: "standing-spot",
    name: "Standing Spot",
    type: "standing_spot",
    lifecycle: "archived",
    price: 10169,
    gstTreatment: "exclusive",
    gstFollowsGlobal: true,
    creditsIncluded: 0,
    packageMixPct: 0,
    peakEligible: true,
    recurring: true,
    discountPct: 0,
    classEligibility: [],
    standingSpotClassesPerWeek: 2,
    standingSpotSeatsPerClass: 1,
    standingSpotMaxSeatsPerClass: 1,
    standingSpotRecurringSubscription: true,
    standingSpotMinCommitmentMonths: 1,
    standingSpotReservedDay: "tue",
    standingSpotReservedTime: "07:00",
    standingSpotCancellationPolicy: "30-day notice after minimum commitment",
    standingSpotPausePolicy: "One 2-week pause per quarter",
    standingSpotMissedClassPolicy: "No refund for no-shows",
    standingSpotMakeUpEligible: true,
    standingSpotComparableProductId: "8-pack",
    standingSpotAutoRenew: true,
    standingSpotMemberAttendanceProbabilityPct: 90,
    standingSpotMemberReleasePolicy: "Release if 24h notice",
    standingSpotReleasedSeatResaleAllowed: true,
    standingSpotExpectedResaleProbabilityPct: 50,
    standingSpotExpectedFlexibleFillProbabilityPct: 85,
    standingSpotRules: {
      recurringSlots: [
        { day: "tue", startTime: "07:00", expectedFlexibleFillProbabilityPct: 90 },
        { day: "thu", startTime: "07:00", expectedFlexibleFillProbabilityPct: 85 },
      ],
      commitmentMonthsOffered: [1, 2],
      defaultCommitmentMonths: 1,
      premiumPct: 0,
      releasePolicy: "makeup_if_released_before_window",
      releaseProbabilityPct: 10,
      resaleProbabilityPct: 50,
    },
  },
  {
    id: "standby",
    name: "Standby",
    type: "standby",
    lifecycle: "archived",
    price: 678,
    gstTreatment: "exclusive",
    gstFollowsGlobal: true,
    creditsIncluded: 1,
    packageMixPct: 0,
    peakEligible: true,
    recurring: false,
    discountPct: 0,
    classEligibility: [],
    standbyReleaseHoursBefore: 3,
    standbyCannibalisationPct: 30,
    maxUsesPerMonth: 4,
    standbyExpectedAvailableEmptySeats: 45,
    standbyExpectedClaimRatePct: 55,
    standbyAttendanceRatePct: 92,
    standingSpotMaxSeatsPerClass: 1,
  },
  {
    id: "intro-trial",
    name: "Intro Trial",
    type: "trial",
    price: 1271,
    gstTreatment: "exclusive",
    gstFollowsGlobal: true,
    creditsIncluded: 1,
    validityDays: 14,
    packageMixPct: 0,
    peakEligible: true,
    recurring: false,
    discountPct: 0,
    classEligibility: ["Intro only"],
    standingSpotMaxSeatsPerClass: 1,
  },
];

export function createSampleAssumptions(): FinanceAssumptions {
  const now = new Date().toISOString();
  return {
    id: "live-assumptions",
    name: "Live Assumptions (SAMPLE)",
    isSample: true,
    updatedAt: now,
    currency: "INR",
    financialYearStartMonth: 4,
    gstRegistered: true,
    gstRatePct: 18,
    priceEntryMode: "exclusive",
    pricingSemanticsVersion: 2,
    reformers: 3,
    maxGroupClassSize: 3,
    operatingDaysPerWeek: 6,
    weeksClosedPerYear: 2,
    plannedHolidays: [],
    classesPerDay: 5,
    useScheduleForCapacity: false,
    schedule: [],
    projectedBookedOccupancyPct: 60,
    projectedAttendedOccupancyPct: 55,
    cancellationRatePct: 5,
    noShowRatePct: 3,
    peakOccupancyPct: 75,
    offPeakOccupancyPct: 45,
    products: syncFlexiblePackageMixFromServiceDemand(
      RAW_SAMPLE_PRODUCTS.map((p) => ensureProductVersionFields(p))
    ),
    accessProductMix: {
      flexiblePackPct: 85,
      standingSpotPct: 0,
      dropInPct: 0,
      standbyPct: 0,
      privateDuoPct: 15,
      trialPct: 0,
    },
    standingSpotEnabled: false,
    standbyEnabled: false,
    privateRequiresExclusiveStudio: false,
    privateSessionsPerMonth: 20,
    privatePrice: 4000,
    privateDurationMinutes: 55,
    privateReformersOccupied: 1,
    privateInstructorCost: 0,
    privateTimeSlot: "Flexible / off-peak",
    duoSessionsPerMonth: 10,
    duoPricePerPerson: 2100,
    duoDurationMinutes: 55,
    duoReformersConsumed: 2,
    duoAvgPeople: 2,
    workshopCountPerMonth: 2,
    workshopPrice: 2500,
    otherRevenuePerMonth: 0,
    rent: 90000,
    camMaintenance: 10000,
    ownerInstructorSalary: 60000,
    includeOwnerMarketRateComp: true,
    additionalInstructorSalary: 0,
    cleanerSalary: 15000,
    receptionSalary: 0,
    security: 5000,
    internet: 2000,
    softwareSubscriptions: 8000,
    accounting: 5000,
    insurance: 4000,
    fixedMarketingRetainer: 10000,
    licences: 2000,
    otherFixedCosts: 5000,
    electricityBase: 8000,
    electricityVariablePerClass: 50,
    laundry: 6000,
    water: 2000,
    cleaningSupplies: 3000,
    sessionConsumables: 30,
    refreshments: 5000,
    paymentGatewayPct: 2,
    paymentGatewayFixedFee: 0,
    instructorPerClassPayout: 0,
    instructorPerAttendeePayout: 0,
    customerAcquisitionSpend: 15000,
    repairsReserve: 3000,
    miscVariableCosts: 2000,
    capexInteriorFitout: 800000,
    capexReformers: 450000,
    capexSmallEquipment: 80000,
    capexMirrors: 60000,
    capexFlooring: 120000,
    capexLighting: 50000,
    capexHvac: 80000,
    capexSoundSystem: 30000,
    capexFurniture: 100000,
    capexReception: 50000,
    capexChangingRoom: 40000,
    capexBathroom: 30000,
    capexSignage: 25000,
    capexWebsite: 50000,
    capexApp: 0,
    capexProfessionalFees: 75000,
    capexLicensingSetup: 25000,
    capexLaunchMarketing: 100000,
    capexInitialConsumables: 20000,
    capexContingency: 150000,
    capexOther: 0,
    securityDepositAmount: 300000,
    securityDepositExpectedRefund: 300000,
    securityDepositImpairmentPct: 0,
    founderEquity: 3250000,
    loanAmount: 0,
    loanInterestRatePct: 12,
    loanTermMonths: 60,
    loanGracePeriodMonths: 0,
    workingCapital: 200000,
    incomeTaxRatePct: 25,
    depreciationAssets: [
      {
        id: "reformers",
        name: "Reformers",
        purchaseValue: 450000,
        inServiceDate: "2026-06-01",
        usefulLifeMonths: 84,
        salvageValue: 50000,
        method: "straight_line",
      },
    ],
    creditBreakageRecognitionPct: 0,
    rampUpMode: "interpolate",
    rampUpStartingOccupancyPct: 30,
    rampUpTargetOccupancyPct: 60,
    rampUpMonthsToTarget: 12,
    rampUpCurve: [],
  creditsSoldOutstanding: 146,
  creditsExpectedRedemptionBeforeExpiry: 128,
  creditsExpectedToExpireUnused: 18,
  peakSlotsShareOfCapacityPct: 50,
  includeRecoverableDepositInPayback: false,
  additionalFundingEvents: [],
  discountRatePct: 10,
  targetOpeningDate: "2026-09-01",
  salesTargetPreferences: {
    targetMonthlyNetProfit: 200_000,
    targetMonth: 8,
    solutionMode: "balanced",
    salesMixMode: "auto",
    avgDropInPurchasesPerCustomerMonth: 1.5,
    avgPrivateSessionsPerClientMonth: 4,
    avgActivePacksPerPackCustomer: 1,
    packRenewalRatePctByProductId: {
      "8-pack": 60,
      "16-pack": 70,
    },
    existingActiveClientsByProductId: {},
    customSalesMixPct: {},
    customSalesQuantitiesByProductId: {},
    targetMonthlyNetSales: 0,
    capacityTightThresholdPct: 85,
  },
  customExpenses: [],
  forecastSettings: {
    forecastYears: 3,
    costEscalationPreset: "base",
    costEscalations: [],
    productPriceGrowth: [],
    forecastTimeline: [],
  },
};
}

export function createSampleDecisions(): Decision[] {
  return [];
}

export function createSampleQuestions(): OpenQuestion[] {
  return [];
}

/** Legacy seed questions — stripped when loading persisted state. */
export const SAMPLE_QUESTION_IDS = new Set(["q-1", "q-2", "q-3"]);

export function stripSampleQuestions(questions: OpenQuestion[]): OpenQuestion[] {
  return questions.filter((q) => !SAMPLE_QUESTION_IDS.has(q.id));
}

export function createSampleActions(): NextAction[] {
  return [];
}

export function createSampleStudios(): Studio[] {
  return [];
}

export function createSampleScenarios(base: FinanceAssumptions): Scenario[] {
  const now = new Date().toISOString();
  const baseCase = {
    ...structuredClone(base),
    name: "Base Case",
  };
  const conservative = {
    ...structuredClone(base),
    name: "Conservative",
    projectedBookedOccupancyPct: 45,
    rampUpTargetOccupancyPct: 45,
  };
  const strongDemand = {
    ...structuredClone(base),
    name: "Strong Demand",
    projectedBookedOccupancyPct: 80,
    rampUpTargetOccupancyPct: 80,
  };
  return [
    {
      id: "scenario-base",
      name: "Base Case",
      description: "Primary planning scenario",
      assumptions: baseCase,
      isBaseCase: true,
      parentScenarioId: undefined,
      timeline: [],
      locked: false,
      archived: false,
      engineVersion: "1.0.0",
      formulaVersion: "2026-09-01",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "scenario-conservative",
      name: "Conservative",
      description: "Lower occupancy stress test",
      assumptions: conservative,
      parentScenarioId: "scenario-base",
      isBaseCase: false,
      timeline: [],
      locked: false,
      archived: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "scenario-strong-demand",
      name: "Strong Demand",
      description: "High occupancy upside case",
      assumptions: strongDemand,
      parentScenarioId: "scenario-base",
      isBaseCase: false,
      timeline: [],
      locked: false,
      archived: false,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function createSampleLibraryItems(): LibraryItem[] {
  return [];
}

export function createSampleSpaceImages(): SpaceImage[] {
  return [];
}

export function createSampleRoadmapItems(): RoadmapItem[] {
  const now = new Date().toISOString();
  return [
    {
      id: "roadmap-1",
      title: "Validate 3-reformer model",
      phase: "Financial validation",
      status: "In progress",
      priority: "High",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "roadmap-2",
      title: "Shortlist 3 locations",
      phase: "Property",
      status: "Todo",
      priority: "High",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "roadmap-3",
      title: "Trademark search for OWN",
      phase: "Brand",
      status: "Todo",
      priority: "Medium",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "roadmap-4",
      title: "Book architect consultation",
      phase: "Build",
      status: "Todo",
      priority: "Medium",
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function createSampleProductConcepts(): ProductConcept[] {
  const now = new Date().toISOString();
  return [
    {
      id: "product-concept-1",
      name: "Booking",
      problem: "Frictionless class booking",
      priority: "MVP",
      status: "Planned",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "product-concept-2",
      name: "Waitlist",
      problem: "Capture unmet demand",
      priority: "MVP",
      status: "Planned",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "product-concept-3",
      name: "Standing Spot",
      problem: "Capacity reservation — certainty of access at a fixed class time",
      priority: "MVP",
      status: "Idea",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "product-concept-4",
      name: "Standby",
      problem: "Monetise expiring capacity",
      priority: "Later",
      status: "Idea",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "product-concept-5",
      name: "Credits",
      problem: "Flexible pack management",
      priority: "MVP",
      status: "Planned",
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function createSampleProgrammingItems(): import("@/lib/finance/schemas").ProgrammingItem[] {
  const now = new Date().toISOString();
  return [
    {
      id: "prog-1",
      name: "Classical Flow",
      classType: "Group",
      level: "All levels",
      status: "Launch",
      credits: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prog-2",
      name: "Contemporary Sculpt",
      classType: "Group",
      level: "Intermediate",
      status: "Testing",
      credits: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prog-3",
      name: "Private Session",
      classType: "Private",
      level: "All",
      status: "Launch",
      credits: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prog-4",
      name: "Standing Spot",
      classType: "Standing Spot",
      level: "All",
      status: "Idea",
      credits: 0,
      createdAt: now,
      updatedAt: now,
    },
  ];
}
