import type { GuideSection } from "./types";

export const profitViewsSection: GuideSection = {
  id: "profit-views",
  title: "Why am I seeing different profit numbers?",
  category: "Math",
  keywords: [
    "profit",
    "different profit",
    "forecast profit",
    "steady state",
    "sales plan",
    "month 8",
    "planning net profit",
    "depreciation",
    "cash vs profit",
    "p&l",
  ],
  aliases: ["profit numbers", "why different profit", "month forecast"],
  body: [
    "You may see different profit numbers in different parts of Own-ed. That does not necessarily mean something is wrong.",
    "Own-ed can look at profit in three different ways depending on the question you're asking. They are three views of the same Planning Net Profit concept — not three different accounting definitions. The difference is what inputs and timeframe are being used.",
    "Think of it like this: (1) What do I expect to make in a particular month? (2) What does a normal, established month look like? (3) What happens if I sell exactly this many things? Those are three different questions, so they can produce three different numbers.",
    "—",
    "1. MONTH X FORECAST PROFIT — answers: \"What does Own-ed expect me to make in this particular month?\" For example, Month 8 Forecast Profit might show ₹66,719 (your actual number will differ). Own-ed looks specifically at Month 8: ramp-up occupancy by then, prices and costs that apply in that month, and any escalation or structural changes scheduled for that month. Early months often have lower occupancy; Month 8 should reflect what Month 8 actually looks like, not what the studio looks like once fully established. Use this when you ask: Will I be profitable by Month 8? How far am I from my ₹2L target in this particular month?",
    "—",
    "2. STEADY-STATE MONTHLY PROFIT — answers: \"What does a normal month look like once the studio reaches the occupancy level I'm planning for?\" This is the Monthly P&L view at your target booked occupancy. It is NOT Month 1, Month 8, or today's calendar month — it is a representative mature month. Example: if you plan for 75% of reformer spots booked long-term, steady-state P&L asks what a normal month at 75% would look like. Use this when you ask: Does this business work once established? Are the long-term economics attractive? Do not compare this directly with Month 2 or Month 5 and assume something is wrong — early ramp months intentionally use lower occupancy.",
    "—",
    "3. YOUR SALES PLAN PROFIT — answers: \"What happens if I sell exactly what I've entered here?\" This is a what-if calculator on Sales & Client Target. If you enter 10 Drop-Ins, 8 eight-credit packs, 4 sixteen-credit packs, and 15 Private sessions, Own-ed calculates what that sales plan would mean. Change the quantities and profit changes. This does not automatically equal Month 8 forecast profit. The forecast is Own-ed saying \"based on all your assumptions, this is what I expect Month 8 to look like.\" Your Sales Plan is you saying \"forget that for a moment — what if I actually sell THIS?\" If all quantities are zero, the plan shows the economics of a zero-sales month (including fixed costs) — not the Month 8 forecast.",
    "—",
    "A SIMPLE EXAMPLE (illustrative only — your numbers will differ): Target Monthly Profit ₹2,00,000. Month 8 Forecast Profit ₹66,719. Gap to Target ₹1,33,281. You want ₹2L; Own-ed expects ₹66,719 in Month 8; you are ₹1,33,281 short. Use Your Sales Plan to test what you would need to sell to close that gap.",
    "—",
    "THE SIMPLEST WAY TO REMEMBER IT: FORECAST = what Own-ed thinks will happen in Month X. STEADY-STATE = what a normal established month looks like at target occupancy. YOUR SALES PLAN = what happens if I sell exactly this?",
    "—",
    "WHY CAN THE NUMBERS BE DIFFERENT? They may use different occupancy levels, months, sales quantities, prices, costs, cost escalations, or business stages. A different number does not automatically mean a bug. But if two screens claim to show the same thing for the same month with the same assumptions and disagree, that should be investigated.",
    "—",
    "WHAT DOES \"PROFIT\" MEAN HERE? Unless a screen says otherwise, Planning Net Profit means: Net Sales (customer revenue after GST) minus Direct Costs (costs that rise when you deliver classes or make sales) minus Operating Expenses (rent, salaries, software, marketing, etc.) minus Depreciation (spreading equipment cost over the years you use it — reduces profit even though that cash already left at purchase) minus Interest (cost of debt) minus Tax = Planning Net Profit.",
    "—",
    "PROFIT IS NOT THE SAME AS CASH. You could show ₹1L of profit but have less than ₹1L of new cash in the bank — or your bank balance could improve even when profit is lower. Cash is also affected by founder funding, loans, equipment purchases, security deposits, loan repayments, and payment timing. Use Profit (P&L) to understand whether the business is economically making money. Use Cash Flow to understand whether you have enough money in the bank to pay bills.",
  ],
  payAttention: [
    "Sales & Client Target forecast profit comes from the monthly projection for your selected month — not from the quantities in Your Sales Plan.",
    "Monthly P&L is steady-state at target occupancy — not a specific ramp-up month.",
    "Depreciation is included in Planning Net Profit even though it is not a monthly cash outflow.",
  ],
  related: [
    { id: "sales-client-target", label: "Sales & Client Target" },
    { id: "pl", label: "P&L" },
    { id: "cash-flow", label: "Cash Flow" },
  ],
};
